<?php

require_once 'Utility/MyException.class.php';
require_once 'DataBase.php';
require_once 'mandrillApi.php';

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of user
 *
 * @author Luis Barreto
 */
class User {

	private $uid;
	private $lname;
	private $fname;
	private $email;
	private $password;
	private $state;
	private $fromFB;
	private $about;
	private $gender;

	//private $userInfoArray;


	public function createUser($userDataArray) {
		$this->fname = $userDataArray['fname'];
		$this->lname = $userDataArray['lname'];
		$this->email = $userDataArray['email'];
		//$this->password = $userDataArray['password'];
		$tempPwd = $userDataArray['password'];
		$this->gender = $userDataArray['gender'];
		$this->state = "p";
		$this->fromFB = $userDataArray['source'];

		//TODO: Look at bookmark class for sample try/catch block around DB code
		$sqlObj = new DataBase();
		$this->password = $this->encyptPwd($tempPwd);
		$query = "INSERT INTO  `db_tackster`.`user_credentials` (
                    `id` ,
                    `email` ,
                    `password` ,
                    `state` ,
                    `fromFB` ,
                    `acct_created`
                )
                VALUES (
                    NULL ,  '$this->email',  '$this->password',  '$this->state',
                    '$this->fromFB', CURRENT_TIMESTAMP
                );";
		$credentialID = $sqlObj->DoQuery($query);
		$query = "INSERT INTO `db_tackster`.`user_profile` (`uc_id`, `id`, `first`,
                `last`, `username`, `sex`, `bio`, `photo`, `timestamp`)
                VALUES
                ('$credentialID', NULL, '$this->fname', '$this->lname', '$this->email', '$this->gender',
                NULL, NULL, CURRENT_TIMESTAMP);";
		$sqlObj->DoQuery($query);
		$sqlObj->destroy();
		$this->sendConfEmail();
	}



	/*
	 * Update user
	 *
	 */
	public function updateUser($userDataArray) {
		//TODO: Implement method
//		throw new MyException('Method createUser() not implemented');

		return TRUE;
	}






#
	# Creates a hash of 128 characters in lenght based on a passphrase.

	#

	#
    public function encyptPwd($string) {
		$passPhrase = "FuckYou!!!";
		$sha512 = hash('sha512', $passPhrase);
		return $sha512;
	}

	public function checkPassword($postPwd, $dbPwd) {
		$match = FALSE;
		$passPhrase = "FuckYou!!!";
		$sha512 = hash('sha512', $postPwd);
		if (strcmp($sha512, $dbPwd) == 0) {
			$match = TRUE;
		} else {
			$match = FALSE;
		}
		return $match;
	}

	public function sendConfEmail() {
		$to = array($this->email => $this->fname . " " . $this->lname);
		$emailObj = new mandrillApi($to, "Welcome to Tackster.com");
		$htmlString = "<html>
                    <h1>Welcome</hi>
                    <p>This is a test email generated by our login system</p>
                    </html>";
		$emailObj->createEmail($htmlString);
		$emailObj->sendEmail();
	}

	public function searchUser($email) {

		//TODO: Look at bookmark class for sample try/catch block around DB code
		$sqlObj = new DataBase();
		$found = FALSE;
		$query = "SELECT *
                    FROM  `user_credentials`
                    WHERE  `email` LIKE  '$email'";
		$sqlObj->DoQuery($query);
		$num = $sqlObj->getNumberOfRecords();
		if ($num > 0) {
			$found = TRUE;
		} else {
			$found = FALSE;
		}
		return $found;
		$sqlObj->destroy();
	}

	public function loadUser($email) {

		//TODO: Look at bookmark class for sample try/catch block around DB code
		$sqlObj = new DataBase();
		$query = "SELECT  `uc_id`, `first` ,  `last` ,  `sex`, `username`
                  FROM  `user_profile`
                  WHERE  `uc_id` = (
                    SELECT  `id`
                    FROM  `user_credentials`
                    WHERE  `email`='{$email}'
                    )
                ";
		$sqlObj->DoQuery($query);
		$result = $sqlObj->GetData();

		//Let's make sure we're only returning one result
		if(count($result) == 1) {
			$result = $result[0];	//break the multi-dimensional array since this should only be 1 record
		} elseif (count($result) > 1) {
			$result = NULL;
			throw new MyException('ERROR: We have duplicate records for User Credential email: {$email}.');
		} else {
			$result = NULL;
		}

		return $result;
	}

	public function logInUser($email, $pwd) {

		//TODO: Look at bookmark class for sample try/catch block around DB code
		$sqlObj = new DataBase();
		$passPhrase = "FuckYou!!!";
		$sha512 = hash('sha512', $pwd);
		$query = "SELECT  `id`, `email` ,  `password` ,  `state` ,  `fromFB`
                    FROM  `user_credentials`
                    WHERE  `email`='{$email}'
                    AND  `password`='{$sha512}'";

		$sqlObj->DoQuery($query);
		$num = $sqlObj->getNumberOfRecords();
		if ($num > 0) {
			// Double check a session already exists, else start one
			if(!isset($_SESSION)) {
				session_start();
			}

			//Set some basic session items
			$_SESSION['loggedin'] = TRUE;

			//create info array
			$_SESSION['profile'] = $this->loadUser($email);
			$_SESSION['uc_id'] = $_SESSION['profile']['uc_id'];	//get user login id
			header('Location: /dashboard/');
		} else {
			$_SESSION['loggedin'] = FALSE;
			throw new MyException('User: ' . $email . 'was not able to login using encrypted password (' . $sha512 . ').');
			header('Location: /auth/login.php');
		}
	}

	public function logOutUser() {
		if (isset($_SESSION)) {
			unset($_SESSION);
			session_unset();
			session_destroy();
		}
		header('Location: /');
	}

	//put your code here
}

?>
