<?php
require_once __DIR__ . '\..\..\..\..\code\includes\Bookmark\SearchBookmark.class.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-25 at 03:23:24.
 */
class SearchBookmarkTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SearchBookmark
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SearchBookmark;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ('search', 72, 3) == $manualentry.
     *
     * @covers SearchBookmark::searchMyTrackBookmarks
     */
    public function testSearchMyTrackBookmarks() {
        $output = $this->object->searchMyTrackBookmarks('search', 72, [3]);
        $output = $output[0];
        
        $this->assertEquals(
                3
                , $output{'id'}
                );
    }

    /**
     * Generated from @assert ('search', 72) == $manualentry.
     *
     * @covers SearchBookmark::searchMyBookmarks
     */
    public function testSearchMyBookmarks() {
        $output = $this->object->searchMyBookmarks('search', 72);
        $output = $output[0];
        $this->assertEquals(
                3
                , $output{'id'} 
        );
    }

    /**
     * Generated from @assert ('search') == $manual entry.
     *
     * @covers SearchBookmark::searchPublicBookmarks
     */
    public function testSearchPublicBookmarks() {
        $output = $this->object->searchPublicBookmarks('search');
        $output = $output[0];
        
        $this->assertEquals(
        3
        , $output{'id'}
        );
    }

}
